version: '2'
services:
    rfbloyalty2-app:
        image: rfbloyalty2
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://rfbloyalty2-mysql:3306/rfbloyalty2?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    rfbloyalty2-mysql:
        extends:
            file: mysql.yml
            service: rfbloyalty2-mysql
